eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/
server:
  port: 8782
spring:
  application:
    name: service-1
  zipkin:
    base-url: http://localhost:9411
  profiles:
    active: dev
#  datasource:
#    url: jdbc:mysql://10.0.131.236:3306/test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: password

mybatis:

  type-aliases-package: com.clt.api.entity

  mapper-locations: classpath*:/mybaits/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
